### ISSUE TITLE
Bintray is shutting down

### ISSUE THREAD

**Issue by tadfisher** [DevSrSouza/compose-icons#1]
Bintray is closing: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

It may be worth applying for coordinates on Maven Central if you own a domain. I can walk you through it if you need guidance.

**Comment by tadfisher** [comment]
The coordinates don't have to match your Java package, you can choose any domain you own.

**Comment by DevSrSouza** [comment]
But it will match the maven group, right?

**Comment by DevSrSouza** [comment]
Update the groupId of the project until there is none alternative for Maven Central and publish it.
