### ISSUE TITLE
"Failed to resolve" error in Android Studio

### ISSUE THREAD

**Issue by jagan999** [DevSrSouza/compose-icons#10]
when I try to use this library in Android Studio Arctic fox, it gives me a "Failed to resolve" error during build. Any suggestions?

**Comment by DevSrSouza** [comment]
Hey @jagan999 , what version are you using? did you add `mavenCentral` to repositories?

**Comment by MuhammedSheref** [comment]
same issue here
**Failed to resolve: br.com.devsrsouza.compose.icons.android:ICON_PACK:1.0.0**

Using Android Studio Arctic Fox | 2020.3.1 Patch 1

**Comment by jagan999** [comment]
Any update on this issue, please? I am unable to use the benefits of this awesome collection of icons because of this resolving issue. Thanks in advance.

**Comment by saulmaos** [comment]
Same issue

**Comment by saulmaos** [comment]
I found the soulution, replace `ICON_PACK` with the pack you want. For example: `font-awesome`
`implementation "br.com.devsrsouza.compose.icons.android:font-awesome:1.0.0"`

**Comment by jagan999** [comment]
Thanks @saulmaos for the solution. Guess it was a silly mistake on my part not to replace the ICON_PACK with the specific pack I wanted. I somehow missed interpreting that part correctly.
