### ISSUE TITLE
Is it save to use this icons in Google Play?

### ISSUE THREAD

**Issue by Monabr** [DevSrSouza/compose-icons#14]
Will i have a problem with copyrights if i will use this icons?

**Comment by DevSrSouza** [comment]
All icons pack provided by the library is open source and their own licensing, you should follow the Icons licensing provided on their docs. (There is a link for it on the icon pack documentation here on the project github)

**Comment by wakaztahir** [comment]
does it increase the size of the apk , or the icons are downloaded as required ?

**Comment by DevSrSouza** [comment]
@wakaztahir It increase the size of the APK. Compose Icons is genereted Compose Vector code, so, is source code this means that if you import a Icon pack of 100 icons but use 15 of then, R8/Proguard should remove all unsed icons from the final build.
So it should of course, contains your icons at the final APK but only the ones you are using.

**Comment by wakaztahir** [comment]
Does it contain these icons https://materialdesignicons.com/

**Comment by wakaztahir** [comment]
If it does not , should I make a pull request , I don't know about licensing but I would love to do this... (if licensing allows it)

**Comment by wakaztahir** [comment]
@DevSrSouza what do you say bro ?

**Comment by wakaztahir** [comment]
I will be making a pull request , This library uses older versions of compose where they may have been separate , I will upgrade kotlin to 1.7.20 , I will update compose as well , I won't change anything in other libraries , I may add some modules for icon packs , make changes to README.md
