### ISSUE TITLE
Support Darwin targets (iOS, MacOS)

### ISSUE THREAD

**Issue by vganin** [DevSrSouza/compose-icons#21]
Since Compose Multiplatform is supporting Darwin targets now, so should this library. Actual supported targets can be inferred from https://mvnrepository.com/artifact/org.jetbrains.compose.ui (https://github.com/JetBrains/compose-jb/blob/master/VERSIONING.md isn't listing new targets for now).

**Comment by DevSrSouza** [comment]
Hi!
I publish the [1.1.0](https://github.com/DevSrSouza/compose-icons/releases/tag/1.1.0) with support for iOS, MacOS em Web (JSCanvas).
