### ISSUE TITLE
Icon Request: Weather Icons

### ISSUE THREAD

**Issue by jordond** [DevSrSouza/compose-icons#3]
It would be awesome if you could add support for [erikflowers/weather-icons](https://erikflowers.github.io/weather-icons/).

I plan on moving one of my projects from Flutter over to Compose, and it relies on those weather icons. I actually created a package for flutter called [weather_icons](https://github.com/worldturtlemedia/weather_icons) that incorporated those icons. So if you need help, or want me to take a stab at forking and adding them, I could try.

One thing to note, in the [README](https://github.com/worldturtlemedia/weather_icons#note) from my repo. I talk about how the icons don't display properly in the default Flutter `Icon` widget, so I created `BoxedIcon` which constrains the icons to a uniform box. I'm not sure if that would be a problem for Compose or not.

**Comment by DevSrSouza** [comment]
Hey @jordond, I hope to add the `erikflowers/weather-icons` in next couple days to the project and publish.

**Comment by DevSrSouza** [comment]
Icon pack add to the project for the new next version (0.2.0)

**Comment by jordond** [comment]
That's awesome!

Thank you 🎉

**Comment by DevSrSouza** [comment]
0.2.0 released in Maven Central with Weather Icons
