### ISSUE TITLE
Add wasmJs support

### ISSUE THREAD

**Issue by Taz03** [DevSrSouza/compose-icons#31]
Add support for Kotlin/WASM builds

**Comment by samoylenkodmitry** [comment]
+1 

`No matching variant of br.com.devsrsouza.compose.icons:feather:1.1.0 was found. The consumer was configured to find a library for use during 'kotlin-runtime', preferably optimized for non-jvm, as well as attribute 'org.jetbrains.kotlin.js.public.package.json' with value 'public-package-json', attribute 'org.jetbrains.kotlin.platform.type' with value 'wasm', attribute 'org.jetbrains.kotlin.wasm.target' with value 'js' but:`

**Comment by Taz03** [comment]
@samoylenkodmitry I just ended up downloading the icon it and using it as a drawable, so you can do that till the support is added

**Comment by DevSrSouza** [comment]
I have not having time in the past year to focus on Compose Icons but this is something that I want to support

**Comment by DevSrSouza** [comment]
Support was added at version `1.1.1`
