### ISSUE TITLE
add Line Awesome Icon Pack

### ISSUE THREAD

**Issue by Vahalaru** [DevSrSouza/compose-icons#4]
Line Awesome Icon Pack would be a good one to add. 
I like the options plus it is free.
[Line Awesome Icon Pack](https://icons8.com/line-awesome)

**Comment by Vahalaru** [comment]
I attempted to make it work using your tool but I must not have something configured correctly. If you don't find it to much trouble to help me figure out what is wrong I would be happy to help add Line Awesome Icon Pack. If not it's cool.

**Comment by DevSrSouza** [comment]
Hi, the icon pack was added, it will be available in the next version (0.2.0)

**Comment by DevSrSouza** [comment]
0.2.0 released to Maven Central with Line Awesome
