### ISSUE TITLE
Support Android via JetBrains' Compose artifact

### ISSUE THREAD

**Issue by chris-hatton** [DevSrSouza/compose-icons#9]
This is an amazing idea and execution (the conversion of SVG to source); but the way it's currently packaged is unusable for me:
**JetBrains' Compose** is (I'm sure you know, but for context) more than just **Desktop**, now encompassing both **Android** and **Web** artifacts too. Putting aside **Web**, which is a different beast, today's **JetBrains Compose** can be most useful when the common API between **Android** and **Desktop** is used (e.g. within some defined `materialComposeMain` source-set).   This is how I'm using it, and it has enabled me to define nearly all of my view delcarations in common code.

But, I can't use your icons from common code as, there seems to be no artifact:
`br.com.devsrsouza.compose.icons.jetbrains:octicons-android:1.0.0`
...so to truly use the icons in a multi-platform way I'd need to import the Android and Desktop artfiacts separately and roll my own `expect`/`actual` for each icon used; which takes away too much of the convenience.

**Comment by DevSrSouza** [comment]
Can you share your Gradle build script of the multiplatform module that uses `compose-icons`?

**Comment by DevSrSouza** [comment]
I'm closing because is inactive, and I could not reproduce, here is working with multiplatform.

**Comment by mpfaff** [comment]
I'm still having this issue
